version: '3'
services:

  feql_mysql_srv:
    container_name: feql_mysql_cnt
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_INITDB_SKIP_TZINFO: 1
    restart: always
    volumes:
      - ./databases:/var/lib/mysql/data
    ports:
      - 4000:3306

  feql_phpmyadmin_srv:
    container_name: feql_phpmyadmin_cnt
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=feql_mysql_srv
     - PMA_PORT=3306
    restart: always
    ports:
      - 4001:80
    volumes:
      - ./phpmyadmin/sessions/:/www/sessions
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./phpmyadmin/theme/:/www/themes/theme/
    depends_on:
      - feql_mysql_srv

  feql_be_srv:
    container_name: feql_be_cnt
    build:
      context: .
      dockerfile: ./app/Dockerfile
    env_file:
      - .env
    environment:
        PHP_EXTENSION_GD: 1
        db_server_name: feql_mysql_srv
        db_server_port: 4000
        db_server_user: root
        db_server_password: secret
        smsto_api_key: ""
        sendgrid_api_key: ""
        bee_dir_path: "/Users/nyolamike/feql/bee/"
        cloudflare_api_token: ""
    volumes:
      - ./app/:/var/www/html/
      - /etc/localtime:/etc/localtime:ro
      - /root/feql_project/created_bees/:/created_bees/
      - /root/feql_project/bee_baas_releases/latest/:/latest_bee/
      - /root/feql_project/bee_baas_releases/configs/:/bee_realease_configs/
      - /etc/nginx/sites-available/:/sites_available/
      - /etc/nginx/sites-enabled/:/sites_enabled/

      # - /Users/nyolamike/feql/created_bees/:/created_bees/
      # - /Users/nyolamike/feql/bee_baas_releases/latest/:/latest_bee/
      # - /Users/nyolamike/feql/bee_baas_releases/configs/:/bee_realease_configs/
      # - /private/etc/nginx/sites-available/:/sites_available/
      # - /private/etc/nginx/sites-enabled/:/sites_enabled/
    ports:
      - 4002:80
    depends_on:
      - feql_phpmyadmin_srv

